# Terraform now owns this secret's full lifecycle, same pattern as the
# Redis module's auth token: the value originates from a resource this
# config itself creates (the tunnel above), so there's no reason to make a
# human copy it into Secrets Manager by hand. The EC2 instance still reads
# it at boot via the IAM role in iam.tf rather than getting it baked into
# user_data directly - keeps the token out of the EC2 launch
# configuration, which is readable via the EC2 API more broadly than
# Secrets Manager access is.
resource "aws_secretsmanager_secret" "tunnel_token" {
  name = "${var.project_name}-${var.environment}-cloudflare-tunnel-token"

  # Same reasoning as the Redis module: this project is built and torn
  # down quickly, and this value is trivially regenerated by re-applying
  # (a fresh tunnel_secret produces a fresh token) - no 30-day recovery
  # window needed, and it would block re-creating the secret under the
  # same name on a fast rebuild.
  recovery_window_in_days = 0

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "tunnel_token" {
  secret_id     = aws_secretsmanager_secret.tunnel_token.id
  secret_string = data.cloudflare_zero_trust_tunnel_cloudflared_token.this.token
}
